### ISSUE TITLE
Need a way to sink ships with 0 health

### ISSUE THREAD

**Issue by TrevorSpear** [OSU-CS361-W17/group6_project4#4]
Some pseudo code that is really well done... didn't test the logic:

public static void Sink(Point shipStart, Point shipEnd, boolean player, BattleshipModel model){

        Point Shot = new Point();

        if(shipStart.getDown() == shipEnd.getDown()){
            int y = shipStart.getDown();
            for (int x = shipStart.getAcross(); x <= shipEnd.getAcross(); x++){
                Shot.setAcross(x);
                Shot.setDown(y);
                
                if( !alreadyShot(Shot, model, player) ){
                    if(player){
                        model.addPointtoArray(Shot, model.getPlayerHits());
                    }else{
                        model.addPointtoArray(Shot, model.getComputerHits());
                    }
                }
            }

        } else if (shipStart.getAcross() == shipEnd.getAcross()) {
            int x = shipStart.getAcross();
            for (int y = shipStart.getDown(); y <= shipEnd.getDown(); y++) {
                Shot.setAcross(x);
                Shot.setDown(y);

                if( !alreadyShot(Shot, model, player) ){
                    if(player){
                        model.addPointtoArray(Shot, model.getPlayerHits());
                    }else{
                        model.addPointtoArray(Shot, model.getComputerHits());
                    }
                }
            }
        }
    }

**Comment by evan-milton** [comment]
Only the clipper is going to sink if hit once, so a hardcode here may not be a big deal

**Comment by evan-milton** [comment]
Nick fixed this in his merge. I shall close the issue.
